name: Deploy to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Add SFTP host key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to SFTP
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_USER: ${{ secrets.SFTP_USER }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_PORT: ${{ secrets.SFTP_PORT }}
        SFTP_DIR: ${{ secrets.SFTP_DIR }}
      run: |
        lftp -e "mirror --reverse --delete --verbose ./ ${SFTP_DIR}; bye" -u ${SFTP_USER},${SFTP_PASSWORD} sftp://${SFTP_HOST}:${SFTP_PORT}